/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entity.KhachHang;
import helper.ConnectDatabase;
import helper.ExcelHelper;
import helper.WordHelper;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author hantr
 */
public class KhachHangF extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangF
     */
    ConnectDatabase ketNoiQLlBH = null;
    Connection connection = null;
    ArrayList<KhachHang> listKhachHang = new ArrayList<>();
    int export = 1;
    // @export :
    //      1 : tất cả
    //      2 : thống kê
    //      3 : tìm kiếm

    public KhachHangF() {
        ketNoiQLlBH = new ConnectDatabase();
        connection = ketNoiQLlBH.getConnection();
        initComponents();
        loadData();
        this.setLocationRelativeTo(null);
        listKhachHang = KhachHang.getAll();
        JTableHeader header = bangkhachhang.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ma = new javax.swing.JRadioButton();
        ten = new javax.swing.JRadioButton();
        dienthoai = new javax.swing.JRadioButton();
        socm = new javax.swing.JRadioButton();
        diachii = new javax.swing.JRadioButton();
        gioitinhhhh = new javax.swing.JRadioButton();
        emaillllll = new javax.swing.JRadioButton();
        timkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        makhachhang = new javax.swing.JTextField();
        tenkhachhang = new javax.swing.JTextField();
        sodienthoai = new javax.swing.JTextField();
        diachi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sochungminh = new javax.swing.JTextField();
        gioitinh = new javax.swing.JComboBox();
        email = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangkhachhang = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TÌM KIẾM");

        buttonGroup1.add(ma);
        ma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ma.setText("Mã khách hàng");

        buttonGroup1.add(ten);
        ten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ten.setText("Tên khách hàng");

        buttonGroup1.add(dienthoai);
        dienthoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dienthoai.setText("Số điện thoại");

        buttonGroup1.add(socm);
        socm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        socm.setText("Số chứng minh ND");

        buttonGroup1.add(diachii);
        diachii.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diachii.setText("Địa chỉ");

        buttonGroup1.add(gioitinhhhh);
        gioitinhhhh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gioitinhhhh.setText("Giới tính");

        buttonGroup1.add(emaillllll);
        emaillllll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emaillllll.setText("Email");

        timkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Thêm file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Xuất file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NHẬP THÔNG TIN  KHÁCH HÀNG");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã khách hàng: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên khách hàng: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoại: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Số chứng minh: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày sinh :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Giới tính :");

        makhachhang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tenkhachhang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        sodienthoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        diachi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Email: ");

        sochungminh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        gioitinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Thêm ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Sửa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Xóa ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Thống kê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        bangkhachhang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bangkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(bangkhachhang);

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("Quay lại");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 102, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        ngaysinh.setDateFormatString("dd-MM-yyyy");
        ngaysinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton11.setBackground(new java.awt.Color(102, 102, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Đăng xuất ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("CỬA HÀNG MÁY VI TÍNH  K-P-T XIN CHÀO QUÝ KHÁCH !");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Nhóm1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Đoàn Văn Tiến");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Hàn Trung Kiên");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Phan Hà Phương");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ma)
                    .addComponent(dienthoai)
                    .addComponent(diachii)
                    .addComponent(emaillllll))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ten)
                            .addComponent(socm)
                            .addComponent(gioitinhhhh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(makhachhang)
                                .addComponent(tenkhachhang)
                                .addComponent(sodienthoai)
                                .addComponent(diachi)
                                .addComponent(sochungminh)
                                .addComponent(gioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email)
                                .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addGap(38, 38, 38)
                                .addComponent(jButton8)))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116))))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton9)
                .addGap(315, 315, 315)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ma)
                            .addComponent(ten))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dienthoai)
                            .addComponent(socm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diachii)
                            .addComponent(gioitinhhhh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emaillllll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton1)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(sochungminh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton6)
                            .addComponent(jButton5)
                            .addComponent(jButton4))
                        .addGap(15, 15, 15)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        makhachhang.setText("");
        tenkhachhang.setText("");
        sodienthoai.setText("");
        diachi.setText("");
        sochungminh.setText("");
        ngaysinh.setDate(null);
        email.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        export = 3;
        // @export :
        //      1 : tất cả
        //      2 : thống kê
        //      3 : tìm kiếm
        if (ma.isSelected()) {
            timKiemTheoMa();
        } else if (ten.isSelected()) {
            timKiemTheoTen();
        } else if (dienthoai.isSelected()) {
            timKiemTheoSoDienThoai();
        } else if (diachii.isSelected()) {
            timKiemTheoDiaChi();
        } else if (socm.isSelected()) {
            timKiemTheoSoChungMinh();
        } else if (gioitinhhhh.isSelected()) {
            timKiemTheoGioiTinh();
        } else if (emaillllll.isSelected()) {
            timKiemTheoEmail();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        listKhachHang = KhachHang.getAll();
        loadData();
        export = 1;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            themKhachHang();
            loadData();
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            suaKhachHang();
            loadData();
            JOptionPane.showMessageDialog(this, "Sửa khách hàng thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int chose = JOptionPane.showConfirmDialog(null, "Xác nhận", "Thêm", 0);
        if (chose == 0) {
            xoaKhachHang();
            loadData();
            JOptionPane.showMessageDialog(this, "Xóa khách hàng thành công!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new ThongKeKhachHangF().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            String type = file.getName().substring(file.getName().lastIndexOf(".") + 1);

            if (type.equals("xls") || type.equals("xlsx")) {
                try {
                    ArrayList<KhachHang> list = ExcelHelper.readKhachHang(file);
                    int re = -1;
                    for (KhachHang o : list) {
                        re = KhachHang.add(o);
                        if (re != 1) {
                            break;
                        }
                    }
                    if (re == 1) {
                        loadData();
                        JOptionPane.showMessageDialog(null, "Thêm thành công");
                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();

//            try {
//                WordHelper.writeKhachHang(file, listKhachHang, "Thông tin khách hàng");
//                JOptionPane.showMessageDialog(null, "Xuất file thành công");
//
//            } catch (IOException ex) {
//                Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, "Xuất file thất bại!");
//            }

            try {
                switch (export) {
                    // @export :
                    //      1 : tất cả
                    //      2 : thống kê
                    //      3 : tìm kiếm
                    case 1:
                        WordHelper.writeKhachHang(file, listKhachHang, "Thông tin khách hàng");
                        break;
//                    case 2:
//                        WordHelper.writeTK(file, tks, "Thống kê nhân viên", thuocTinh);
//                        break;
                    case 3:
                        WordHelper.writeKhachHang(file, listKhachHang, "Tìm kiếm khách hàng");
                        break;
                    case 0:

                }
                JOptionPane.showMessageDialog(null, "Xuất file thành công");
            } catch (IOException ex) {
                Logger.getLogger(NhanVienUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        TrangChu main = new TrangChu();
        main.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangkhachhang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diachi;
    private javax.swing.JRadioButton diachii;
    private javax.swing.JRadioButton dienthoai;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton emaillllll;
    private javax.swing.JComboBox gioitinh;
    private javax.swing.JRadioButton gioitinhhhh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton ma;
    private javax.swing.JTextField makhachhang;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private javax.swing.JTextField sochungminh;
    private javax.swing.JRadioButton socm;
    private javax.swing.JTextField sodienthoai;
    private javax.swing.JRadioButton ten;
    private javax.swing.JTextField tenkhachhang;
    private javax.swing.JTextField timkiem;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bangkhachhang.removeAll();
        String sql = "select * from khachhang ; ";
        String[] columns = {"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Số chứng minh", "Ngày sinh", "Giới tính", "Email"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("maKhachHang"));
                vector.add(resultSet.getString("tenKhachHang"));
                vector.add(resultSet.getString("sdtKhachHang"));
                vector.add(resultSet.getString("diachi"));
                vector.add(resultSet.getString("soCMT"));
                vector.add(resultSet.getDate("ngaySinh"));
                vector.add(resultSet.getString("gioiTinh"));
                vector.add(resultSet.getString("emailKhachHang"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangkhachhang.setModel(model);
        bangkhachhang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (bangkhachhang.getSelectedRow() >= 0) {
                    makhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 0).toString());
                    tenkhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 1).toString());
                    sodienthoai.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 2).toString());
                    diachi.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 3).toString());
                    sochungminh.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 4).toString());
                    ngaysinh.setDate((Date) bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 5));
                    gioitinh.setSelectedItem(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 6).toString());
                    email.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 7).toString());

                }
            }
        });
    }
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    private void timKiemTheoMa() {
        int input = Integer.parseInt(timkiem.getText());
        String sql = "select * from khachhang where maKhachHang like '%" + input + "%'; ";

        thucThiSqlTimKiem(sql);
    }

    private void thucThiSqlTimKiem(String sql) {
        bangkhachhang.removeAll();
        String[] columns = {"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Số chứng minh", "Ngày sinh", "Giới tính", "Email"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        Statement statement = null;
        ResultSet resultSet = null;
        listKhachHang.clear();
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("maKhachHang"));
                vector.add(resultSet.getString("tenKhachHang"));
                vector.add(resultSet.getString("sdtKhachHang"));
                vector.add(resultSet.getString("diachi"));
                vector.add(resultSet.getString("soCMT"));
                vector.add(resultSet.getDate("ngaySinh"));
                vector.add(resultSet.getString("gioiTinh"));
                vector.add(resultSet.getString("emailKhachHang"));

                listKhachHang.add(new KhachHang(resultSet.getInt("maKhachHang"),
                        resultSet.getString("tenKhachHang"),
                        resultSet.getString("sdtKhachHang"),
                        resultSet.getString("diachi"),
                        resultSet.getString("soCMT"),
                        resultSet.getDate("ngaySinh"),
                        resultSet.getString("gioiTinh"),
                        resultSet.getString("emailKhachHang")));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangkhachhang.setModel(model);
        bangkhachhang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (bangkhachhang.getSelectedRow() >= 0) {
                    makhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 0).toString());
                    tenkhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 1).toString());
                    sodienthoai.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 2).toString());
                    diachi.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 3).toString());
                    sochungminh.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 4).toString());
                    ngaysinh.setDate((Date) bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 5));
                    gioitinh.setSelectedItem(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 6).toString());
                    email.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 7).toString());

                }
            }
        });
    }

    private void timKiemTheoTen() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where lower(tenKhachHang) like '%" + input.toLowerCase() + "%'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoSoDienThoai() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where sdtKhachHang like '%" + input + "%'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoDiaChi() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where lower(diaChi) like '%" + input.toLowerCase() + "%'";
        System.out.println(sql);
        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoSoChungMinh() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where soCMT ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoGioiTinh() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where lower(gioiTinh) like '" + input.toLowerCase() + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoEmail() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where lower(emailKhachHang) like '%"
                + input.toLowerCase() + "%'; ";

        thucThiSqlTimKiem(sql);
    }

    private void themKhachHang() throws SQLException {

        int maKhachHang = Integer.parseInt(makhachhang.getText().toString());
        String tenKhachHang = tenkhachhang.getText();
        String sdtKhachHang = sodienthoai.getText();
        String diaChi = diachi.getText();
        String soCMT = sochungminh.getText();
        String ngaySinh = dateFormat.format(ngaysinh.getDate());
        String gioiTinh = gioitinh.getSelectedItem().toString();
        String emailKhachHang = email.getText();
        String sql = "insert into khachhang (maKhachHang, tenKhachHang, sdtKhachHang , diachi, soCMT, ngaySinh,gioiTinh, emailKhachHang ) values ('" + maKhachHang + "','" + tenKhachHang + "', '" + sdtKhachHang + "', '" + diaChi + "', '" + soCMT + "', '" + ngaySinh + "', '" + gioiTinh + "', '" + emailKhachHang + "');";
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);

    }

    private void suaKhachHang() throws SQLException {
        int maKhachHang = Integer.parseInt(makhachhang.getText().toString());
        String tenKhachHang = tenkhachhang.getText();
        String sdtKhachHang = sodienthoai.getText();
        String diaChi = diachi.getText();
        String soCMT = sochungminh.getText();
        String ngaySinh = dateFormat.format(ngaysinh.getDate());
        String gioiTinh = gioitinh.getSelectedItem().toString();
        String emailKhachHang = email.getText();
        String sql = "update  khachhang set   tenKhachHang='" + tenKhachHang + "', sdtKhachHang='" + sdtKhachHang + "',diachi='" + diaChi + "',soCMT='" + soCMT + "',ngaySinh='" + ngaySinh + "',gioiTinh='" + gioiTinh + "',emailKhachHang='" + emailKhachHang + "'   where maKhachHang='" + maKhachHang + "';";
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void xoaKhachHang() {

        try {
            int maKhachHang = Integer.parseInt(makhachhang.getText());
            String sql = "delete from khachhang where maKhachHang = " + maKhachHang;
            Statement statement = null;
            ResultSet resultSet = null;

            statement = connection.createStatement();
            statement.executeUpdate(sql);
        } catch (SQLException ex) {
            
        }
    }

}
