/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entity.MayTinh;
import entity.MayTinhChiTiet;
import helper.ConnectDatabase;
import helper.ExcelHelper;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author hantr
 */
public class MayTinhChiTietF extends javax.swing.JFrame {

    ConnectDatabase ketNoiQLlBH = null;
    Connection connection = null;
    /**
     * Creates new form MayTinhChiTietF
     */

    ArrayList<MayTinhChiTiet> listMayTinhChiTiets = MayTinhChiTiet.getAll();

    public MayTinhChiTietF() throws ClassNotFoundException, SQLException {
        ketNoiQLlBH = new ConnectDatabase();
        connection = ketNoiQLlBH.getConnection();
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);

        comboboxMaMayTinhChiTiet();
        comboboxGiaBan();
        comboboxGiaNhap();
        comboboxMauSac();
        mamaytinhtt.setText("" + MayTinhF.docMaMayTinh());
        loadData();
        JTableHeader header = bangmaytinhchitiet.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 14));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangmaytinhchitiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mamaytinhtt = new javax.swing.JTextField();
        machitiettt = new javax.swing.JTextField();
        motatt = new javax.swing.JTextField();
        gianhaptt = new javax.swing.JTextField();
        giabantt = new javax.swing.JTextField();
        cauhinhtt = new javax.swing.JTextField();
        mausactt = new javax.swing.JTextField();
        tonkhott = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mamaytinhchitietR = new javax.swing.JRadioButton();
        gianhapR = new javax.swing.JRadioButton();
        giabanR = new javax.swing.JRadioButton();
        mausacR = new javax.swing.JRadioButton();
        mamaytinhchitietI = new javax.swing.JComboBox();
        gianhapcbb = new javax.swing.JComboBox();
        giabancbb = new javax.swing.JComboBox();
        maucbb = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("CỬA HÀNG MÁY VI TÍNH  K-P-T XIN CHÀO QUÝ KHÁCH !");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        bangmaytinhchitiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bangmaytinhchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bangmaytinhchitiet);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NHẬP THÔNG TIN MÁY TÍNH CHI TIẾT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã máy tính chi tiết: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mô tả: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Giá nhập :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giá bán: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cấu hình: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Màu sắc: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng tồn kho: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Danh sách máy tính chi tiết của mã máy tính: ");

        mamaytinhtt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        machitiettt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        motatt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        gianhaptt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        giabantt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cauhinhtt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mausactt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tonkhott.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Reset ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Quay lại ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("TÌM KIẾM");

        buttonGroup1.add(mamaytinhchitietR);
        mamaytinhchitietR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mamaytinhchitietR.setText("Mã máy tính chi tiết ");

        buttonGroup1.add(gianhapR);
        gianhapR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gianhapR.setText("Giá nhập ");

        buttonGroup1.add(giabanR);
        giabanR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giabanR.setText("Giá bán ");

        buttonGroup1.add(mausacR);
        mausacR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mausacR.setText("Màu sắc");

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Tìm kiếm ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Thêm ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Sửa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("Xóa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("Thêm file");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 102, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("Xuất file");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(102, 102, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Đăng xuất");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("CỬA HÀNG MÁY VI TÍNH  K-P-T XIN CHÀO QUÝ KHÁCH !");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Nhóm1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Đoàn Văn Tiến");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Hàn Trung Kiên");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Phan Hà Phương");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(91, 91, 91))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(machitiettt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(motatt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gianhaptt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(giabantt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cauhinhtt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mausactt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tonkhott, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton7)
                                .addGap(45, 45, 45)
                                .addComponent(jButton8)
                                .addGap(43, 43, 43)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jButton5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mamaytinhchitietR)
                                            .addComponent(gianhapR)
                                            .addComponent(giabanR)
                                            .addComponent(mausacR))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gianhapcbb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(giabancbb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maucbb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mamaytinhchitietI, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(303, 303, 303)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mamaytinhtt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {giabancbb, gianhapcbb, mamaytinhchitietI, maucbb});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(machitiettt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(motatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(gianhaptt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(giabantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cauhinhtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(mausactt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(mamaytinhchitietI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mamaytinhchitietR)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gianhapR)
                                    .addComponent(gianhapcbb, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(giabanR)
                                    .addComponent(giabancbb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maucbb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mausacR))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tonkhott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mamaytinhtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new MayTinhF().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (mamaytinhchitietR.isSelected()) {

            timKiemTheoMaMayTinhChiTiet();
        } else if (gianhapR.isSelected()) {

            timKiemTheoGiaNhap();
        } else if (giabanR.isSelected()) {

            timKiemTheoGiaBan();
        } else if (mausacR.isSelected()) {
            timKiemTheoMauSac();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            themMayTinhChiTiet();
        } catch (SQLException ex) {
            Logger.getLogger(MayTinhChiTietF.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
        JOptionPane.showMessageDialog(this, "Thêm máy tính chi tiết thành công!");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            suaMayTinhChiTiet();
        } catch (SQLException ex) {
            Logger.getLogger(MayTinhF.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
        JOptionPane.showMessageDialog(this, "Sửa máy tính thành công!");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int chose = JOptionPane.showConfirmDialog(null, "Xác nhận", "Thêm", 0);
        if (chose == 0) {
            try {
                xoaMayTinhChiTiet();
            } catch (SQLException ex) {
                Logger.getLogger(MayTinhF.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadData();
            JOptionPane.showMessageDialog(this, "Xóa máy tính thành công!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            String type = file.getName().substring(file.getName().lastIndexOf(".") + 1);
            System.out.println(type);

            if (type.equals("xls") || type.equals("xlsx")) {
                try {
                    ArrayList<MayTinhChiTiet> list = ExcelHelper.readMayTinhChiTiet(file);
                    System.out.println(list.size() + "");
                    int re = -1;
                    for (MayTinhChiTiet o : list) {
                        re = MayTinhChiTiet.add(o);
                        if (re != 1) {
                            break;
                        }
                    }
                    if (re == 1) {
                        loadData();
                        JOptionPane.showMessageDialog(null, "Thêm thành công");
                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    Logger.getLogger(MayTinh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayTinhChiTietF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayTinhChiTietF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayTinhChiTietF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayTinhChiTietF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MayTinhChiTietF().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MayTinhChiTietF.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MayTinhChiTietF.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangmaytinhchitiet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cauhinhtt;
    private javax.swing.JRadioButton giabanR;
    private javax.swing.JComboBox giabancbb;
    private javax.swing.JTextField giabantt;
    private javax.swing.JRadioButton gianhapR;
    private javax.swing.JComboBox gianhapcbb;
    private javax.swing.JTextField gianhaptt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField machitiettt;
    private javax.swing.JComboBox mamaytinhchitietI;
    private javax.swing.JRadioButton mamaytinhchitietR;
    private javax.swing.JTextField mamaytinhtt;
    private javax.swing.JComboBox maucbb;
    private javax.swing.JRadioButton mausacR;
    private javax.swing.JTextField mausactt;
    private javax.swing.JTextField motatt;
    private javax.swing.JTextField tonkhott;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bangmaytinhchitiet.removeAll();
        String[] columns = new String[]{"Mã máy tính chi tiết", "Mã máy tính", "Mô tả", "Giá nhập", "Giá bán", "Cấu hình", "Màu sắc", "Số lượng tồn kho"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from maytinhchitiet where maMayTinh = '" + MayTinhF.docMaMayTinh() + "'; ";
        System.out.println(sql);
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("maMayTinhChiTiet"));
                vector.add(resultSet.getInt("maMayTinh"));
                vector.add(resultSet.getString("moTa"));
//                vector.add(resultSet.getDouble("giaNhap"));
                vector.add(new DecimalFormat("##").format(resultSet.getDouble("giaNhap")));
                vector.add(new DecimalFormat("##").format(resultSet.getDouble("giaBan")));
                vector.add(resultSet.getString("cauHinh"));
                vector.add(resultSet.getString("mauSac"));
                vector.add(resultSet.getInt("soLuongTonKho"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangmaytinhchitiet.setModel(model);

        bangmaytinhchitiet.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (bangmaytinhchitiet.getSelectedRow() >= 0) {
                    machitiettt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 0).toString());
                    mamaytinhtt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 1).toString());
                    motatt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 2).toString());
                    gianhaptt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 3).toString());
                    giabantt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 4).toString());
                    cauhinhtt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 5).toString());
                    mausactt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 6).toString());
                    tonkhott.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 7).toString());

                }
            }
        });
    }

    private void reset() {
        machitiettt.setText("");
        motatt.setText("");
        gianhaptt.setText("");
        giabantt.setText("");
        cauhinhtt.setText("");
        mausactt.setText("");
        tonkhott.setText("");

    }

    public void comboboxMaMayTinhChiTiet() {

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < listMayTinhChiTiets.size(); i++) {
            if (listMayTinhChiTiets.get(i).getMaMayTinh() == MayTinhF.docMaMayTinh()) {
                model.addElement(listMayTinhChiTiets.get(i).getMaMayTinhChiTiet());
            }
        }
        mamaytinhchitietI.setModel(model);

    }

    public void comboboxGiaNhap() {

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < listMayTinhChiTiets.size(); i++) {
            if (listMayTinhChiTiets.get(i).getMaMayTinh() == MayTinhF.docMaMayTinh()) {
                model.addElement(new DecimalFormat("##").format(listMayTinhChiTiets.get(i).getGiaNhap()));
            }
        }
        gianhapcbb.setModel(model);

    }

    public void comboboxGiaBan() {

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < listMayTinhChiTiets.size(); i++) {
            if (listMayTinhChiTiets.get(i).getMaMayTinh() == MayTinhF.docMaMayTinh()) {
                model.addElement(new DecimalFormat("##").format(listMayTinhChiTiets.get(i).getGiaBan()));
            }
        }
        giabancbb.setModel(model);

    }

    public void comboboxMauSac() {

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < listMayTinhChiTiets.size(); i++) {
            if (listMayTinhChiTiets.get(i).getMaMayTinh() == MayTinhF.docMaMayTinh()) {
                model.addElement(listMayTinhChiTiets.get(i).getMauSac());
            }
        }
        maucbb.setModel(model);

    }

    private void timKiemTheoMaMayTinhChiTiet() {
        String sql = "select * from maytinhchitiet where maMayTinhChiTiet = " + mamaytinhchitietI.getSelectedItem();
        System.out.println(sql);
        thucThiSqlTimKiem(sql);
        
    }

    private void timKiemTheoGiaNhap() {
        String sql = "select * from maytinhchitiet where giaNhap = " + gianhapcbb.getSelectedItem() + " and maMayTinh=" + MayTinhF.docMaMayTinh() + ";";
        System.out.println(sql);
        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoGiaBan() {
        String sql = "select * from maytinhchitiet where giaBan = " + giabancbb.getSelectedItem() + " and maMayTinh=" + MayTinhF.docMaMayTinh() + ";";
        System.out.println(sql);
        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoMauSac() {
        String sql = "select * from maytinhchitiet where mauSac ='" + maucbb.getSelectedItem() + "' and maMayTinh=" + MayTinhF.docMaMayTinh() + ";";
        System.out.println(sql);
        thucThiSqlTimKiem(sql);
    }

    private void thucThiSqlTimKiem(String sql) {
        
        String[] columns = new String[]{"Mã máy tính chi tiết", "Mã máy tính", "Mô tả", "Giá nhập", "Giá bán", "Cấu hình", "Màu sắc", "Số lượng tồn kho"};

        DefaultTableModel model = new DefaultTableModel(columns, 0);

        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("maMayTinhChiTiet"));
                vector.add(resultSet.getInt("maMayTinh"));
                vector.add(resultSet.getString("moTa"));
                vector.add(resultSet.getDouble("giaNhap"));
                vector.add(resultSet.getDouble("giaBan"));
                vector.add(resultSet.getString("cauHinh"));
                vector.add(resultSet.getString("mauSac"));
                vector.add(resultSet.getInt("soLuongTonKho"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangmaytinhchitiet.setModel(model);
        bangmaytinhchitiet.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (bangmaytinhchitiet.getSelectedRow() >= 0) {
                    machitiettt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 0).toString());
                    mamaytinhtt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 1).toString());
                    motatt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 2).toString());
                    gianhaptt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 3).toString());
                    giabantt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 4).toString());
                    cauhinhtt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 5).toString());
                    mausactt.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 6).toString());
                    tonkhott.setText(bangmaytinhchitiet.getValueAt(bangmaytinhchitiet.getSelectedRow(), 7).toString());

                }
            }
        });
    }

    private void themMayTinhChiTiet() throws SQLException {
        //doc id
        String ma = machitiettt.getText();
        int maMayTinhChiTiet = Integer.parseInt(ma);

        //doc ten 
        String moTa = motatt.getText();
        //
        String gianhap = gianhaptt.getText();
        Double giaNhap = Double.parseDouble(gianhap);
        //
        String giaban = giabantt.getText();
        Double giaBan = Double.parseDouble(giaban);
        //
        String cauHinh = cauhinhtt.getText();
        //
        String mauSac = mausactt.getText();
        int maMayTinh = MayTinhF.docMaMayTinh();

        //
        String soluongtonkho = tonkhott.getText();
        int soLuongTonKho = Integer.parseInt(soluongtonkho);

        String sql = "insert into maytinhchitiet (maMayTinhChiTiet, maMayTinh,moTa, giaNhap, giaBan, cauHinh,mauSac , soLuongTonKho ) values ('" + maMayTinhChiTiet + "','" + maMayTinh + "', '" + moTa + "', '" + giaNhap + "', '" + giaBan + "', '" + cauHinh + "', '" + mauSac + "', '" + soLuongTonKho + "');";
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void suaMayTinhChiTiet() throws SQLException {
        //doc id
        String ma = machitiettt.getText();
        int maMayTinhChiTiet = Integer.parseInt(ma);

        //doc ten 
        String moTa = motatt.getText();
        //
        String gianhap = gianhaptt.getText();
        Double giaNhap = Double.parseDouble(gianhap);
        //
        String giaban = giabantt.getText();
        Double giaBan = Double.parseDouble(giaban);
        //
        String cauHinh = cauhinhtt.getText();
        //
        String mauSac = mausactt.getText();
        int maMayTinh = MayTinhF.docMaMayTinh();

        //
        String soluongtonkho = tonkhott.getText();
        int soLuongTonKho = Integer.parseInt(soluongtonkho);

        String sql = "update  maytinhchitiet set   moTa='" + moTa + "', giaNhap='" + giaNhap + "',giaBan='" + giaBan + "',cauHinh='" + cauHinh + "',mauSac='" + mauSac + "',soLuongTonKho='" + soLuongTonKho + "'   where maMayTinhChiTiet='" + maMayTinhChiTiet + "';";

        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void xoaMayTinhChiTiet() throws SQLException {
        String ma = machitiettt.getText();
        int maMayTinhChiTiet = Integer.parseInt(ma);

        String sql = "delete from maytinhchitiet where maMayTinhChiTiet = " + maMayTinhChiTiet;
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);
    }
}
